# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1fb71dfad2649ecfbdc1f33cf9ebee22befc52ec70c280532bec0313f575b22fb3b93ba9f1c46ea6ea4dc0fb96a41b0f21ddbbdb2e0b66a71db41867675f367

test:
  secret_key_base: 8a3681bd15accbcf4718446f65ff8f043cef443de0d383692558dbfd91445e0a8a8a21b067292f18b9202bdcde71bfe4fac26a2f1915bf39e82ce419cfb353f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
